/**
 * Created by densh on 02.11.2016.
 */
public enum TokenType {
    NUMBER,
    KEYWORD,
    OPERATION,
    LOGICAL_OPERATION,
    COMPARATOR,
    SEPARATOR_CIRCURAL,
    SEPARATOR_WAVE,
    SEPARATOR_SQUARE,
    SEPARATOR_EXIT,
    VARIABLE
}
